### ISSUE TITLE
Poster art for TV shows is too large in some email clients

### ISSUE THREAD

**Issue by troycarpenter** [bstascavage/plexReport#41] opened 2015-02-06 18:47 UTC
The poster art used for the TV shows looks to be rendering at full size, whereas the poster art for movies seems right-sized.

I see this when using Outlook.  One other user in the Plex forum reports (with screenshots) the same issue using Thunderbird.

I have not seen the issue when using Roundcube, a web-based email client.  Perhaps that's because the email client is purposely resizing the images to fit on the screen better, but that is speculation.

**Comment by StevenDTX** [comment] 2015-02-11 20:01
I just wanted to throw this out there. If you feel it isnt relevant, this post can be deleted.

For grins, I put together a quick PowerShell script that output some HTML and sent an email.  Even though the photo size is clearly spelled out in the html code, Outlook made it full size.  I tried it on three different clients. So, it looks like Outlook does some screwy stuff.

**Comment by troycarpenter** [comment] 2015-02-11 20:43
Great feedback.  If the correct HTML code is there (which I suspect it is because other clients seem to render correctly), there's nothing that can be done.

**Comment by bstascavage** [comment] 2015-02-12 15:05
Every email client does their own thing when rendering HTML in emails.  It is sorta like the wild, wild west.  

The Thunderbird thing is an old bug that is now fixed.  As stated before, however, it is a slippery slop when it comes to supporting multiply email clients, as each one needs its own tweaks, and regression testing with every new update.  That, combined with Outlook not being free, makes me not want to support any additional email clients at this time.

**Closed by bstascavage** 2015-02-12 15:05 UTC
